using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Atelier.Application.Combos.Commands;
using Atelier.Application.Combos.Queries;

namespace Atelier.Api.Controllers.Products;

[ApiController]
[Route("api/[controller]")]
public class CombosController : ControllerBase
{
    private readonly IMediator _mediator;

    public CombosController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [Authorize(Roles = "Admin")]
    [HttpGet]
    public async Task<IActionResult> GetAll(
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20,
        [FromQuery] bool? isActive = null,
        [FromQuery] bool? isAutoGenerated = null,
        [FromQuery] string? search = null)
    {
        var result = await _mediator.Send(new GetAllCombosQuery
        {
            Page = page,
            PageSize = pageSize,
            IsActive = isActive,
            IsAutoGenerated = isAutoGenerated,
            Search = search,
        });
        return Ok(result);
    }

    [Authorize(Roles = "Admin")]
    [HttpGet("{id}")]
    public async Task<IActionResult> GetById(int id)
    {
        var result = await _mediator.Send(new GetComboByIdQuery { Id = id });
        if (result == null) return NotFound();
        return Ok(result);
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> Create([FromBody] CreateComboCommand command)
    {
        var id = await _mediator.Send(command);
        return CreatedAtAction(nameof(GetById), new { id }, new { id });
    }

    [Authorize(Roles = "Admin")]
    [HttpPut("{id}")]
    public async Task<IActionResult> Update(int id, [FromBody] UpdateComboCommand command)
    {
        command.Id = id;
        await _mediator.Send(command);
        return NoContent();
    }

    [Authorize(Roles = "Admin")]
    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(int id)
    {
        await _mediator.Send(new DeleteComboCommand { Id = id });
        return NoContent();
    }

    [Authorize(Roles = "Admin")]
    [HttpPatch("{id}/approve")]
    public async Task<IActionResult> Approve(int id, [FromBody] ApproveComboRequest? body)
    {
        await _mediator.Send(new ApproveComboCommand
        {
            Id = id,
            DiscountOverride = body?.DiscountOverride,
        });
        return NoContent();
    }

    [Authorize(Roles = "Admin")]
    [HttpPatch("{id}/toggle")]
    public async Task<IActionResult> Toggle(int id)
    {
        await _mediator.Send(new ToggleComboActiveCommand { Id = id });
        return NoContent();
    }

    [HttpGet("product/{productId}")]
    public async Task<IActionResult> GetForProduct(int productId)
    {
        var result = await _mediator.Send(new GetCombosForProductQuery { ProductId = productId });
        return Ok(result);
    }

    [HttpPost("check-cart")]
    public async Task<IActionResult> CheckCart([FromBody] CheckCartCombosQuery query)
    {
        var result = await _mediator.Send(query);
        return Ok(result);
    }
}

public class ApproveComboRequest
{
    public decimal? DiscountOverride { get; set; }
}
