using Atelier.Application.Common.Interfaces;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Atelier.Application.Combos.Commands;

public class CreateComboCommand : IRequest<int>
{
    public string Name { get; set; } = null!;
    public string? Description { get; set; }
    public List<int> ProductIds { get; set; } = new();
    public string DiscountType { get; set; } = "Percentage";
    public decimal DiscountValue { get; set; }
    public int MaxUses { get; set; } = 0;
}

public class CreateComboCommandHandler
    : IRequestHandler<CreateComboCommand, int>
{
    private readonly IApplicationDbContext _context;

    public CreateComboCommandHandler(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<int> Handle(CreateComboCommand request, CancellationToken cancellationToken)
    {
        var products = await _context.Products
            .Where(p => request.ProductIds.Contains(p.Id))
            .ToListAsync(cancellationToken);

        if (products.Count != request.ProductIds.Count)
            throw new Exception("Một số sản phẩm không tồn tại.");

        var combo = new Domain.Entities.ProductCombo
        {
            Name = request.Name,
            Description = request.Description,
            DiscountType = request.DiscountType,
            DiscountValue = request.DiscountValue,
            MaxUses = request.MaxUses,
            CurrentUses = 0,
            IsActive = true,
            IsAutoGenerated = false,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
        };

        foreach (var productId in request.ProductIds)
        {
            combo.Items.Add(new Domain.Entities.ProductComboItem
            {
                ProductId = productId,
            });
        }

        _context.ProductCombos.Add(combo);
        await _context.SaveChangesAsync(cancellationToken);

        return combo.Id;
    }
}
