using Atelier.Application.Common.Interfaces;
using Atelier.Application.Common.Models;
using Atelier.Application.DTOs;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Atelier.Application.Combos.Queries;

public class GetAllCombosQuery : IRequest<PaginatedList<ProductComboAdminDto>>
{
    public int Page { get; set; } = 1;
    public int PageSize { get; set; } = 20;
    public bool? IsActive { get; set; }
    public bool? IsAutoGenerated { get; set; }
    public string? Search { get; set; }
}

public class GetAllCombosQueryHandler
    : IRequestHandler<GetAllCombosQuery, PaginatedList<ProductComboAdminDto>>
{
    private readonly IApplicationDbContext _context;

    public GetAllCombosQueryHandler(IApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<PaginatedList<ProductComboAdminDto>> Handle(
        GetAllCombosQuery request, CancellationToken cancellationToken)
    {
        var query = _context.ProductCombos
            .Include(c => c.Items)
                .ThenInclude(i => i.Product)
                    .ThenInclude(p => p.ProductVariants)
                        .ThenInclude(v => v.ProductVariantImages)
            .AsQueryable();

        if (request.IsActive.HasValue)
            query = query.Where(c => c.IsActive == request.IsActive.Value);

        if (request.IsAutoGenerated.HasValue)
            query = query.Where(c => c.IsAutoGenerated == request.IsAutoGenerated.Value);

        if (!string.IsNullOrWhiteSpace(request.Search))
            query = query.Where(c => c.Name.Contains(request.Search));

        var totalCount = await query.CountAsync(cancellationToken);

        var combos = await query
            .OrderByDescending(c => c.WeightedUtility)
            .ThenByDescending(c => c.Lift)
            .Skip((request.Page - 1) * request.PageSize)
            .Take(request.PageSize)
            .ToListAsync(cancellationToken);

        var dtos = combos.Select(MapToAdminDto).ToList();

        return new PaginatedList<ProductComboAdminDto>(dtos, totalCount, request.Page, request.PageSize);
    }

    internal static ProductComboAdminDto MapToAdminDto(Domain.Entities.ProductCombo combo)
    {
        return new ProductComboAdminDto
        {
            Id = combo.Id,
            Name = combo.Name,
            Description = combo.Description,
            Products = combo.Items.Select(i => new ProductDto
            {
                Id = i.Product.Id,
                Name = i.Product.Name ?? "",
                Slug = i.Product.Slug ?? "",
                MinPrice = i.Product.ProductVariants.Any()
                    ? i.Product.ProductVariants.Min(v => v.Price) : 0m,
                MaxPrice = i.Product.ProductVariants.Any()
                    ? i.Product.ProductVariants.Max(v => v.Price) : 0m,
                ThumbnailUrl = i.Product.ProductVariants
                    .Where(v => v.IsDefault)
                    .SelectMany(v => v.ProductVariantImages)
                    .OrderByDescending(img => img.IsPrimary)
                    .Select(img => img.ImageUrl)
                    .FirstOrDefault()
                    ?? i.Product.ProductVariants
                        .SelectMany(v => v.ProductVariantImages)
                        .OrderByDescending(img => img.IsPrimary)
                        .Select(img => img.ImageUrl)
                        .FirstOrDefault(),
                IsInStock = i.Product.ProductVariants.Any(v => v.Quantity > 0),
            }).ToList(),
            DiscountType = combo.DiscountType,
            DiscountValue = combo.DiscountValue,
            SuggestedDiscountValue = combo.SuggestedDiscountValue,
            OriginalTotalPrice = combo.Items.Sum(i => i.Product.ProductVariants.Any()
                ? i.Product.ProductVariants.Min(v => v.Price) : 0m),
            ComboPrice = combo.DiscountType switch
            {
                "Percentage" => Math.Round(combo.Items.Sum(i => i.Product.ProductVariants.Any()
                    ? i.Product.ProductVariants.Min(v => v.Price) : 0m) * (1 - combo.DiscountValue / 100m), 0),
                "Fixed" => Math.Max(0, combo.Items.Sum(i => i.Product.ProductVariants.Any()
                    ? i.Product.ProductVariants.Min(v => v.Price) : 0m) - combo.DiscountValue),
                _ => combo.Items.Sum(i => i.Product.ProductVariants.Any()
                    ? i.Product.ProductVariants.Min(v => v.Price) : 0m),
            },
            MaxUses = combo.MaxUses,
            CurrentUses = combo.CurrentUses,
            Support = combo.Support,
            Confidence = combo.Confidence,
            Lift = combo.Lift,
            WeightedUtility = combo.WeightedUtility,
            IsActive = combo.IsActive,
            IsAutoGenerated = combo.IsAutoGenerated,
            CreatedAt = combo.CreatedAt,
        };
    }
}
