using Atelier.Application.Common.Interfaces;
using Atelier.Application.Recommendations.Services;
using Atelier.Domain.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace Atelier.Infrastructure.Services;

public class ComboSuggestionService : BackgroundService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<ComboSuggestionService> _logger;

    public ComboSuggestionService(IServiceProvider serviceProvider, ILogger<ComboSuggestionService> logger)
    {
        _serviceProvider = serviceProvider;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("ComboSuggestionService started.");

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await GenerateComboSuggestionsAsync(stoppingToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating combo suggestions.");
            }

            await Task.Delay(TimeSpan.FromHours(24), stoppingToken);
        }
    }

    private async Task GenerateComboSuggestionsAsync(CancellationToken cancellationToken)
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<IApplicationDbContext>();
        var recommender = new AprioriRecommender(context);

        _logger.LogInformation("Generating combo suggestions: Apriori → HUI...");

        var frequentItemsets = await recommender.GenerateFrequentItemsetsAsync(cancellationToken);
        _logger.LogInformation("Apriori found {Count} frequent itemsets (2-4 items).", frequentItemsets.Count);

        var itemsets = await recommender.GenerateHighUtilityItemsetsAsync(frequentItemsets, cancellationToken);
        _logger.LogInformation("HUI found {Count} high-utility combos from Apriori candidates.", itemsets.Count);

        var existingCombos = await context.ProductCombos
            .Include(c => c.Items)
            .ToListAsync(cancellationToken);

        var existingHashes = existingCombos
            .ToDictionary(
                c => string.Join(",", c.Items.Select(i => i.ProductId).OrderBy(x => x)),
                c => c);

        var newCombosCount = 0;
        var updatedCombosCount = 0;

        foreach (var itemset in itemsets)
        {
            if (itemset.ProductIds.Count < 2) continue;

            var hashKey = string.Join(",", itemset.ProductIds.OrderBy(x => x));

            if (existingHashes.TryGetValue(hashKey, out var existingCombo))
            {
                existingCombo.Support = itemset.Support;
                existingCombo.Confidence = itemset.Confidence;
                existingCombo.Lift = itemset.Lift;
                existingCombo.WeightedUtility = itemset.WeightedUtility;
                existingCombo.SuggestedDiscountValue = itemset.SuggestedDiscountPercent;
                existingCombo.UpdatedAt = DateTime.UtcNow;
                updatedCombosCount++;
            }
            else
            {
                var combo = new ProductCombo
                {
                    Name = $"Combo #{string.Join("-", itemset.ProductIds.Take(3))}",
                    DiscountType = "Percentage",
                    DiscountValue = itemset.SuggestedDiscountPercent,
                    SuggestedDiscountValue = itemset.SuggestedDiscountPercent,
                    Support = itemset.Support,
                    Confidence = itemset.Confidence,
                    Lift = itemset.Lift,
                    WeightedUtility = itemset.WeightedUtility,
                    IsActive = false,
                    IsAutoGenerated = true,
                    MaxUses = 0,
                    CurrentUses = 0,
                    CreatedAt = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow,
                };

                foreach (var productId in itemset.ProductIds)
                {
                    combo.Items.Add(new ProductComboItem
                    {
                        ProductId = productId,
                    });
                }

                context.ProductCombos.Add(combo);
                newCombosCount++;
            }
        }

        await context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation(
            "Combo suggestions done: {New} new, {Updated} updated.",
            newCombosCount, updatedCombosCount);

        try
        {
            await BackfillWeightedUtilityAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Backfill WeightedUtility failed.");
        }
    }

    private async Task BackfillWeightedUtilityAsync(CancellationToken cancellationToken)
    {
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<IApplicationDbContext>();

        var combosToBackfill = await context.ProductCombos
            .Include(c => c.Items)
            .Where(c => c.WeightedUtility == 0)
            .ToListAsync(cancellationToken);

        combosToBackfill = combosToBackfill.Where(c => c.Items.Count >= 2).ToList();

        if (combosToBackfill.Count == 0)
        {
            _logger.LogInformation("No combos need WeightedUtility backfill.");
            return;
        }

        _logger.LogInformation("Backfilling WeightedUtility for {Count} old combos...", combosToBackfill.Count);

        foreach (var combo in combosToBackfill)
        {
            try
            {
                var comboProductIds = combo.Items.Select(i => i.ProductId).ToHashSet();

                var allItems = await context.OrderItems
                    .Where(oi => oi.Order.OrderStatus == "Completed" && oi.ProductVariant != null)
                    .Select(oi => new { oi.OrderId, oi.ProductVariant!.ProductId, oi.Quantity, oi.UnitPrice })
                    .ToListAsync(cancellationToken);

                var matchCount = 0;
                var totalRevenue = 0m;

                foreach (var group in allItems.GroupBy(x => x.OrderId))
                {
                    var orderProductIds = group.Select(x => x.ProductId).ToHashSet();
                    if (comboProductIds.IsSubsetOf(orderProductIds))
                    {
                        matchCount++;
                        foreach (var item in group.Where(x => comboProductIds.Contains(x.ProductId)))
                        {
                            totalRevenue += item.Quantity * item.UnitPrice;
                        }
                    }
                }

                if (matchCount == 0)
                {
                    _logger.LogInformation("Combo {Name}: no matching orders, skipping.", combo.Name);
                    continue;
                }

                var avgUtility = totalRevenue / matchCount;
                var weightedUtility = avgUtility * (decimal)Math.Log2(matchCount + 1);

                combo.WeightedUtility = Math.Round(weightedUtility, 0);
                combo.UpdatedAt = DateTime.UtcNow;

                _logger.LogInformation("Combo {Name}: WU={WU}, Txns={Txn}, Avg={Avg}",
                    combo.Name, combo.WeightedUtility, matchCount, avgUtility);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Backfill failed for combo {Name}.", combo.Name);
            }
        }

        await context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Backfill completed for {Count} combos.", combosToBackfill.Count);
    }
}
