namespace Atelier.Domain.Entities;

public class ProductCombo
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public string? Description { get; set; }

    public string DiscountType { get; set; } = null!;
    public decimal DiscountValue { get; set; }
    public decimal? SuggestedDiscountValue { get; set; }

    public int MaxUses { get; set; }
    public int CurrentUses { get; set; }

    public double Support { get; set; }
    public double Confidence { get; set; }
    public double Lift { get; set; }
    public decimal WeightedUtility { get; set; }

    public bool IsActive { get; set; }
    public bool IsAutoGenerated { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ProductComboItem> Items { get; set; } = new List<ProductComboItem>();
}
