namespace Atelier.Application.DTOs;

public class ProductComboAdminDto
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public string? Description { get; set; }
    public List<ProductDto> Products { get; set; } = new();
    public int ProductCount => Products.Count;
    public string DiscountType { get; set; } = null!;
    public decimal DiscountValue { get; set; }
    public decimal? SuggestedDiscountValue { get; set; }
    public decimal OriginalTotalPrice { get; set; }
    public decimal ComboPrice { get; set; }
    public int MaxUses { get; set; }
    public int CurrentUses { get; set; }
    public double Support { get; set; }
    public double Confidence { get; set; }
    public double Lift { get; set; }
    public decimal WeightedUtility { get; set; }
    public bool IsActive { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
}

public class ProductComboCustomerDto
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public string? Description { get; set; }
    public List<ProductDto> Products { get; set; } = new();
    public string DiscountType { get; set; } = null!;
    public decimal DiscountValue { get; set; }
    public decimal OriginalTotalPrice { get; set; }
    public decimal ComboPrice { get; set; }
    public bool IsAvailable { get; set; }
    public string? UnavailableReason { get; set; }
}

public class CartComboCheckResult
{
    public List<ApplicableComboDto> ApplicableCombos { get; set; } = new();
}

public class ApplicableComboDto
{
    public int ComboId { get; set; }
    public string ComboName { get; set; } = null!;
    public List<int> MatchingProductIds { get; set; } = new();
    public List<int> MissingProductIds { get; set; } = new();
    public decimal DiscountAmount { get; set; }
    public decimal ComboPrice { get; set; }
    public decimal OriginalPrice { get; set; }
    public bool AllItemsInCart { get; set; }
}
