"use client";

import { useEffect, useState, useCallback } from "react";
import { combos as combosApi, products as productsApi } from "@/lib/api";
import type { ProductComboAdminDto, ProductAdminDto, PaginatedList, CreateComboRequest } from "@/lib/types";
import { useConfirm } from "@/components/ConfirmDialog";
import { useToast } from "@/components/Toast";

export default function CombosPage() {
  const toast = useToast();
  const { confirm } = useConfirm();
  const [data, setData] = useState<PaginatedList<ProductComboAdminDto> | null>(null);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [filter, setFilter] = useState<"all" | "active" | "suggested" | "inactive">("all");
  const [search, setSearch] = useState("");
  const [showModal, setShowModal] = useState(false);
  const [editingCombo, setEditingCombo] = useState<ProductComboAdminDto | null>(null);
  const [showApproveModal, setShowApproveModal] = useState<ProductComboAdminDto | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<ProductComboAdminDto | null>(null);
  const [allProducts, setAllProducts] = useState<ProductAdminDto[]>([]);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const params: Record<string, unknown> = { page, pageSize: 15, search: search || undefined };
      if (filter === "active") params.isActive = true;
      else if (filter === "inactive") params.isActive = false;
      else if (filter === "suggested") { params.isAutoGenerated = true; params.isActive = false; }

      const result = await combosApi.list(params as Parameters<typeof combosApi.list>[0]);
      setData(result);
    } catch { }
    setLoading(false);
  }, [page, filter, search]);

  useEffect(() => { loadData(); }, [loadData]);

  useEffect(() => {
    productsApi.admin({ pageSize: 200 }).then((res) => {
      const items = (res as unknown as { items?: ProductAdminDto[] }).items;
      if (items) setAllProducts(items);
    }).catch(() => {});
  }, []);

  async function handleToggle(combo: ProductComboAdminDto) {
    try {
      await combosApi.toggle(combo.id);
      toast.showToast(combo.isActive ? "Đã tắt combo" : "Đã kích hoạt combo", "success");
      loadData();
    } catch (err: unknown) {
      toast.showToast(err instanceof Error ? err.message : "Lỗi", "error");
    }
  }

  async function handleDelete() {
    if (!deleteTarget) return;
    const ok = await confirm(`Bạn có chắc muốn xóa combo "${deleteTarget.name}"?`);
    if (!ok) return;
    try {
      await combosApi.delete(deleteTarget.id);
      toast.showToast("Đã xóa combo", "success");
      setDeleteTarget(null);
      loadData();
    } catch (err: unknown) {
      toast.showToast(err instanceof Error ? err.message : "Lỗi", "error");
    }
  }

  async function handleApprove(discountOverride?: number) {
    if (!showApproveModal) return;
    try {
      await combosApi.approve(showApproveModal.id, discountOverride);
      toast.showToast("Đã duyệt combo", "success");
      setShowApproveModal(null);
      loadData();
    } catch (err: unknown) {
      toast.showToast(err instanceof Error ? err.message : "Lỗi", "error");
    }
  }

  async function handleSaveCombo(formData: CreateComboRequest, comboId?: number) {
    try {
      if (comboId) {
        await combosApi.update(comboId, formData);
        toast.showToast("Đã cập nhật combo", "success");
      } else {
        await combosApi.create(formData);
        toast.showToast("Đã tạo combo mới", "success");
      }
      setShowModal(false);
      setEditingCombo(null);
      loadData();
    } catch (err: unknown) {
      toast.showToast(err instanceof Error ? err.message : "Lỗi", "error");
    }
  }

  function formatCurrency(v: number) {
    return new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" }).format(v);
  }

  function formatPercent(v: number) {
    return (v * 100).toFixed(1) + "%";
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="font-headline-lg text-headline-lg">COMBO</h1>
        <button
          onClick={() => { setEditingCombo(null); setShowModal(true); }}
          className="bg-primary text-on-primary px-6 py-3 rounded-full font-label-caps text-label-caps hover:opacity-90 transition"
        >
          + TẠO COMBO
        </button>
      </div>

      <div className="flex items-center gap-4">
        <div className="flex gap-2">
          {(["all", "active", "suggested", "inactive"] as const).map((f) => (
            <button
              key={f}
              onClick={() => { setFilter(f); setPage(1); }}
              className={`px-4 py-2 rounded-full font-label-caps text-label-caps transition ${
                filter === f ? "bg-primary text-on-primary" : "bg-surface-container-high text-on-surface-variant hover:bg-surface-container-highest"
              }`}
            >
              {f === "all" ? "Tất cả" : f === "active" ? "Đang kích hoạt" : f === "suggested" ? "Chờ duyệt" : "Tắt"}
            </button>
          ))}
        </div>
        <input
          type="text"
          placeholder="Tìm kiếm combo..."
          value={search}
          onChange={(e) => { setSearch(e.target.value); setPage(1); }}
          className="flex-1 px-4 py-2 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none focus:ring-2 focus:ring-primary"
        />
      </div>

      <div className="bg-surface-container rounded-xl overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-outline-variant/30">
              <th className="text-left px-6 py-4 font-label-caps text-label-caps text-on-surface-variant">Tên combo</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">SP</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">Tỷ lệ xuất hiện</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">Giá trị TB/đơn</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">Giảm giá</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">Giá combo</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">Đã bán</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">Trạng thái</th>
              <th className="text-center px-4 py-4 font-label-caps text-label-caps text-on-surface-variant">Hành động</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={9} className="text-center py-8 text-on-surface-variant">Đang tải...</td></tr>
            ) : !data || data.items.length === 0 ? (
              <tr><td colSpan={9} className="text-center py-8 text-on-surface-variant">Không có combo nào</td></tr>
            ) : data.items.map((combo) => (
              <tr key={combo.id} className="border-b border-outline-variant/20 hover:bg-surface-container-high/50 transition">
                <td className="px-6 py-4">
                  <div className="font-body-lg text-body-lg">{combo.name}</div>
                  <div className="font-body-sm text-body-sm text-on-surface-variant mt-1">
                    {combo.isAutoGenerated && (
                      <span className="inline-block px-2 py-0.5 bg-surface-container-high text-on-surface-variant rounded-full text-[10px] font-label-caps mr-2">AUTO</span>
                    )}
                    {combo.description || "Không có mô tả"}
                  </div>
                  <div className="flex flex-wrap gap-1 mt-2">
                    {combo.products.map((p) => (
                      <span key={p.id} className="inline-flex items-center gap-1 px-2 py-0.5 bg-surface-container-high rounded-full text-[10px]">
                        {p.thumbnailUrl && <img src={p.thumbnailUrl} alt="" className="w-4 h-4 rounded-full object-cover" />}
                        {p.name}
                      </span>
                    ))}
                  </div>
                </td>
                <td className="text-center px-4 py-4 font-body-md text-body-md">{combo.productCount}</td>
                <td className="text-center px-4 py-4 font-body-sm text-body-sm">{formatPercent(combo.support)}</td>
                <td className="text-center px-4 py-4 font-body-sm text-body-sm font-medium">{formatCurrency(combo.weightedUtility)}</td>
                <td className="text-center px-4 py-4">
                  <span className="font-body-md text-body-md text-primary font-semibold">
                    {combo.discountType === "Percentage" ? `${combo.discountValue}%` : formatCurrency(combo.discountValue)}
                  </span>
                  {combo.suggestedDiscountValue && (
                    <div className="text-[10px] text-on-surface-variant">Gợi ý: {combo.suggestedDiscountValue}%</div>
                  )}
                </td>
                <td className="text-center px-4 py-4">
                  <div className="text-[10px] text-on-surface-variant line-through">{formatCurrency(combo.originalTotalPrice)}</div>
                  <span className="font-body-md text-body-md text-secondary font-semibold">{formatCurrency(combo.comboPrice)}</span>
                </td>
                <td className="text-center px-4 py-4 font-body-sm text-body-sm">
                  {combo.maxUses > 0 ? `${combo.currentUses}/${combo.maxUses}` : combo.currentUses}
                </td>
                <td className="text-center px-4 py-4">
                  {combo.isActive ? (
                    <span className="inline-block px-3 py-1 bg-primary-container text-on-primary-container rounded-full font-label-caps text-[10px]">Active</span>
                  ) : (
                    <span className="inline-block px-3 py-1 bg-surface-container-high text-on-surface-variant rounded-full font-label-caps text-[10px]">Tắt</span>
                  )}
                </td>
                <td className="px-4 py-4">
                  <div className="flex items-center justify-center gap-2">
                    {!combo.isActive && combo.isAutoGenerated && (
                      <button
                        onClick={() => setShowApproveModal(combo)}
                        className="p-2 rounded-lg bg-primary-container text-on-primary-container hover:opacity-80 transition"
                        title="Duyệt"
                      >
                        <span className="material-symbols-outlined text-[18px]">check</span>
                      </button>
                    )}
                    <button
                      onClick={() => { setEditingCombo(combo); setShowModal(true); }}
                      className="p-2 rounded-lg bg-surface-container-high text-on-surface-variant hover:bg-surface-container-highest transition"
                      title="Sửa"
                    >
                      <span className="material-symbols-outlined text-[18px]">edit</span>
                    </button>
                    <button
                      onClick={() => handleToggle(combo)}
                      className="p-2 rounded-lg bg-surface-container-high text-on-surface-variant hover:bg-surface-container-highest transition"
                      title={combo.isActive ? "Tắt" : "Bật"}
                    >
                      <span className="material-symbols-outlined text-[18px]">{combo.isActive ? "visibility_off" : "visibility"}</span>
                    </button>
                    <button
                      onClick={() => setDeleteTarget(combo)}
                      className="p-2 rounded-lg bg-error-container text-on-error-container hover:opacity-80 transition"
                      title="Xóa"
                    >
                      <span className="material-symbols-outlined text-[18px]">delete</span>
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {data && data.totalPages > 1 && (
        <div className="flex items-center justify-center gap-2">
          <button
            disabled={!data.hasPreviousPage}
            onClick={() => setPage((p) => p - 1)}
            className="px-4 py-2 rounded-lg bg-surface-container-high font-label-caps text-label-caps disabled:opacity-40"
          >
            Trước
          </button>
          <span className="font-body-md text-body-md text-on-surface-variant px-4">
            {data.page}/{data.totalPages}
          </span>
          <button
            disabled={!data.hasNextPage}
            onClick={() => setPage((p) => p + 1)}
            className="px-4 py-2 rounded-lg bg-surface-container-high font-label-caps text-label-caps disabled:opacity-40"
          >
            Sau
          </button>
        </div>
      )}

      {showModal && (
        <ComboModal
          combo={editingCombo}
          allProducts={allProducts}
          onClose={() => { setShowModal(false); setEditingCombo(null); }}
          onSave={handleSaveCombo}
        />
      )}

      {showApproveModal && (
        <ApproveModal
          combo={showApproveModal}
          onClose={() => setShowApproveModal(null)}
          onApprove={handleApprove}
        />
      )}

      {deleteTarget && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={() => setDeleteTarget(null)}>
          <div className="bg-surface rounded-2xl w-full max-w-md p-6" onClick={(e) => e.stopPropagation()}>
            <h3 className="font-headline-sm text-headline-sm mb-4">Xóa combo</h3>
            <p className="font-body-md text-body-md text-on-surface-variant mb-6">
              Bạn có chắc muốn xóa combo &quot;{deleteTarget.name}&quot;?
            </p>
            <div className="flex justify-end gap-3">
              <button onClick={() => setDeleteTarget(null)} className="px-6 py-3 rounded-full bg-surface-container-high font-label-caps text-label-caps">Hủy</button>
              <button onClick={handleDelete} className="px-6 py-3 rounded-full bg-error text-on-error font-label-caps text-label-caps">Xóa</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function ComboModal({
  combo,
  allProducts,
  onClose,
  onSave,
}: {
  combo: ProductComboAdminDto | null;
  allProducts: ProductAdminDto[];
  onClose: () => void;
  onSave: (data: CreateComboRequest, id?: number) => void;
}) {
  const [name, setName] = useState(combo?.name || "");
  const [description, setDescription] = useState(combo?.description || "");
  const [discountType, setDiscountType] = useState(combo?.discountType || "Percentage");
  const [discountValue, setDiscountValue] = useState(combo?.discountValue?.toString() || "");
  const [maxUses, setMaxUses] = useState(combo?.maxUses?.toString() || "0");
  const [selectedIds, setSelectedIds] = useState<number[]>(combo?.products?.map((p) => p.id) || []);
  const [productSearch, setProductSearch] = useState("");
  const [saving, setSaving] = useState(false);

  const filteredProducts = allProducts.filter(
    (p) =>
      !selectedIds.includes(p.id) &&
      (p.name.toLowerCase().includes(productSearch.toLowerCase()) || productSearch === "")
  );

  function toggleProduct(id: number) {
    setSelectedIds((prev) => prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]);
  }

  async function handleSubmit() {
    if (!name || selectedIds.length < 2 || !discountValue) return;
    setSaving(true);
    await onSave(
      {
        name,
        description: description || undefined,
        productIds: selectedIds,
        discountType,
        discountValue: parseFloat(discountValue),
        maxUses: parseInt(maxUses) || 0,
      },
      combo?.id
    );
    setSaving(false);
  }

  function formatCurrency(v: number) {
    return new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" }).format(v);
  }

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-surface rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="p-6 border-b border-outline-variant/30">
          <h2 className="font-headline-sm text-headline-sm">{combo ? "Sửa combo" : "Tạo combo mới"}</h2>
        </div>
        <div className="p-6 space-y-4">
          <div>
            <label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">Tên combo *</label>
            <input value={name} onChange={(e) => setName(e.target.value)} className="w-full px-4 py-3 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none focus:ring-2 focus:ring-primary" />
          </div>
          <div>
            <label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">Mô tả</label>
            <input value={description} onChange={(e) => setDescription(e.target.value)} className="w-full px-4 py-3 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none focus:ring-2 focus:ring-primary" />
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div>
              <label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">Loại giảm giá</label>
              <select value={discountType} onChange={(e) => setDiscountType(e.target.value)} className="w-full px-4 py-3 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none">
                <option value="Percentage">Phần trăm (%)</option>
                <option value="Fixed">Cố định (VND)</option>
              </select>
            </div>
            <div>
              <label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">Giá trị giảm *</label>
              <input type="number" value={discountValue} onChange={(e) => setDiscountValue(e.target.value)} className="w-full px-4 py-3 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none focus:ring-2 focus:ring-primary" />
            </div>
            <div>
              <label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">Giới hạn lượt (0=vô hạn)</label>
              <input type="number" value={maxUses} onChange={(e) => setMaxUses(e.target.value)} className="w-full px-4 py-3 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none focus:ring-2 focus:ring-primary" />
            </div>
          </div>
          <div>
            <label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">Sản phẩm trong combo * (tối thiểu 2)</label>
            <div className="flex flex-wrap gap-2 mb-2">
              {selectedIds.map((id) => {
                const p = allProducts.find((x) => x.id === id);
                if (!p) return null;
                return (
                  <span key={id} className="inline-flex items-center gap-1 px-3 py-1.5 bg-primary-container text-on-primary-container rounded-full font-body-sm text-body-sm">
                    {p.thumbnailUrl && <img src={p.thumbnailUrl} alt="" className="w-5 h-5 rounded-full object-cover" />}
                    {p.name}
                    <button onClick={() => toggleProduct(id)} className="ml-1 hover:opacity-60">&times;</button>
                  </span>
                );
              })}
            </div>
            <input
              type="text"
              placeholder="Tìm sản phẩm để thêm..."
              value={productSearch}
              onChange={(e) => setProductSearch(e.target.value)}
              className="w-full px-4 py-2 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none focus:ring-2 focus:ring-primary mb-2"
            />
            <div className="max-h-48 overflow-y-auto space-y-1">
              {filteredProducts.slice(0, 20).map((p) => (
                <button
                  key={p.id}
                  onClick={() => toggleProduct(p.id)}
                  className="flex items-center gap-2 w-full px-3 py-2 rounded-lg hover:bg-surface-container-high transition text-left"
                >
                  {p.thumbnailUrl && <img src={p.thumbnailUrl} alt="" className="w-8 h-8 rounded object-cover" />}
                  <span className="font-body-sm text-body-sm flex-1">{p.name}</span>
                  <span className="font-body-sm text-body-sm text-on-surface-variant">{formatCurrency(p.minPrice)}</span>
                </button>
              ))}
            </div>
          </div>
        </div>
        <div className="p-6 border-t border-outline-variant/30 flex justify-end gap-3">
          <button onClick={onClose} className="px-6 py-3 rounded-full bg-surface-container-high font-label-caps text-label-caps hover:bg-surface-container-highest transition">Hủy</button>
          <button
            onClick={handleSubmit}
            disabled={saving || !name || selectedIds.length < 2 || !discountValue}
            className="px-6 py-3 rounded-full bg-primary text-on-primary font-label-caps text-label-caps hover:opacity-90 transition disabled:opacity-40"
          >
            {saving ? "Đang lưu..." : combo ? "Cập nhật" : "Tạo combo"}
          </button>
        </div>
      </div>
    </div>
  );
}

function ApproveModal({
  combo,
  onClose,
  onApprove,
}: {
  combo: ProductComboAdminDto;
  onClose: () => void;
  onApprove: (discountOverride?: number) => void;
}) {
  const [discount, setDiscount] = useState(combo.suggestedDiscountValue?.toString() || combo.discountValue.toString());
  const [useSuggested, setUseSuggested] = useState(!!combo.suggestedDiscountValue);

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-surface rounded-2xl w-full max-w-md" onClick={(e) => e.stopPropagation()}>
        <div className="p-6 border-b border-outline-variant/30">
          <h2 className="font-headline-sm text-headline-sm">Duyệt combo</h2>
        </div>
        <div className="p-6 space-y-4">
          <p className="font-body-md text-body-md text-on-surface-variant">
            Combo: <strong>{combo.name}</strong> ({combo.productCount} sản phẩm)
          </p>
          <p className="font-body-sm text-body-sm text-on-surface-variant">
            Support: {(combo.support * 100).toFixed(1)}% | Lift: {combo.lift.toFixed(2)}
          </p>
          {combo.suggestedDiscountValue && (
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={useSuggested}
                onChange={(e) => {
                  setUseSuggested(e.target.checked);
                  if (e.target.checked) setDiscount(combo.suggestedDiscountValue!.toString());
                }}
                className="w-4 h-4 accent-primary"
              />
              <span className="font-body-sm text-body-sm">
                Áp dụng gợi ý: <strong>{combo.suggestedDiscountValue}%</strong>
              </span>
            </label>
          )}
          <div>
            <label className="font-label-caps text-label-caps text-on-surface-variant block mb-2">
              {combo.discountType === "Percentage" ? "Phần trăm giảm (%)" : "Giá trị giảm (VND)"}
            </label>
            <input
              type="number"
              value={discount}
              onChange={(e) => setDiscount(e.target.value)}
              className="w-full px-4 py-3 bg-surface-container-high rounded-lg font-body-md text-body-md outline-none focus:ring-2 focus:ring-primary"
            />
          </div>
        </div>
        <div className="p-6 border-t border-outline-variant/30 flex justify-end gap-3">
          <button onClick={onClose} className="px-6 py-3 rounded-full bg-surface-container-high font-label-caps text-label-caps hover:bg-surface-container-highest transition">Hủy</button>
          <button
            onClick={() => onApprove(parseFloat(discount))}
            className="px-6 py-3 rounded-full bg-primary text-on-primary font-label-caps text-label-caps hover:opacity-90 transition"
          >
            Duyệt combo
          </button>
        </div>
      </div>
    </div>
  );
}
